import Head from 'next/head'
import NavBar from '../components/Ui/NavBar/NavBar'
import HomeSolution from './HomeSolution'
import Work from './Work'
import Carousel from './IndusExpert'
import Blog from './Blog'

export default function Home () {
  return (
    <>
      <Head>
        <title>ATC Chain</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,800;1,100;1,200;1,300&display=swap'
          rel='stylesheet'
        />

        {/* </link> */}
      </Head>
      <NavBar />
      <Blog />
      {/* <HomeSolution /> */}
      {/* <Work /> */}
    </>
  )
}
